// State de productos
export const OBTENER_PRODUCTOS_EXITO = 'OBTENER_PRODUCTOS_EXITO';

// State para el Pedido
export const SELECCIONAR_PRODUCTO = 'SELECCIONAR_PRODUCTO';
export const CONFIRMAR_ORDENAR_PLATILLO = 'CONFIRMAR_ORDENAR_PLATILLO';
export const MOSTRAR_RESUMEN = 'MOSTRAR_RESUMEN';
export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO';
export const PEDIDO_ORDENADO = 'PEDIDO_ODENADO';

// State para las reservas
export const OBTENER_RESERVAS_EXITO = 'OBTENER_RESERVAS_EXITO';

//state para reservas
export const CONFIRMAR_RESERVA = 'CONFIRMAR_RESERVA';
export const ELIMINAR_RESERVA = 'ELIMINAR_RESERVA';
export const RESERVA_REALIZADA = 'RESERVA_REALIZADA';

//state para usuarios
export const OBTENER_USUARIOS_EXITO = 'OBTENER_USUARIOS_EXITO';
export const OBTENER_ROL_EXITO = 'OBTENER_ROL_EXITO';

//state para meseros
export const OBTENER_ORDENES_EXITO = 'OBTENER_ORDENES_EXITO';
